

services:
  mongo_db:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - 27017:27017

  app:
    depends_on:
      - mongo_db
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/todo
